### ISSUE TITLE
Setting task in example code fails

### ISSUE THREAD

**Issue by frankroeder** [iglu-contest/gridworld#14]
I tried to execute the example of the usage section. Here is the full stack trace:

```bash
Traceback (most recent call last):
  File "/Users/frankroeder/Documents/python/iglu_2022/test.py", line 11, in <module>
    env.set_task(DUMMY_TASK)
  File "/Users/frankroeder/miniforge3/envs/iglu_2022/lib/python3.9/site-packages/gridworld/env.py", line 153, in set_task
    self.reset()
  File "/Users/frankroeder/miniforge3/envs/iglu_2022/lib/python3.9/site-packages/gridworld/env.py", line 234, in reset
    obs['pov'] = self.render()[..., :-1]
  File "/Users/frankroeder/miniforge3/envs/iglu_2022/lib/python3.9/site-packages/gridworld/env.py", line 240, in render
    return self.renderer.render()
  File "/Users/frankroeder/miniforge3/envs/iglu_2022/lib/python3.9/site-packages/gridworld/render.py", line 122, in render
    return np.asanyarray(
ValueError: cannot reshape array of size 65536 into shape (64,64,4)
```

**Comment by artemZholus** [comment]
Hello, this is a known issue that, to the best of our knowledge, happens only on devices with mac os. I will fix the issue and notify you. Please provide your python version and your os.

**Comment by frankroeder** [comment]
Thank you for the answer. I am using `Python 3.9.13` and macOS Monterey Version 12.4 (21F79).

**Comment by chenhch8** [comment]
Hi, I also had the similar problem `cannot reshape array of size 0 into shape (64,64,4)`. I am using `python3.8` and `linux-16.04`. Here is the stack trace: 
```
(pid=25888)   File "/usr/local/lib/python3.8/dist-packages/gym/core.py", line 292, in reset
(pid=25888)     return self.env.reset(**kwargs)
(pid=25888)   File "/usr/local/lib/python3.8/dist-packages/gym/wrappers/order_enforcing.py", line 16, in reset
(pid=25888)     return self.env.reset(**kwargs)
(pid=25888)   File "/usr/local/lib/python3.8/dist-packages/gridworld/env.py", line 288, in reset
(pid=25888)     return super().reset()
(pid=25888)   File "/usr/local/lib/python3.8/dist-packages/gym/core.py", line 292, in reset
(pid=25888)     return self.env.reset(**kwargs)
(pid=25888)   File "/usr/local/lib/python3.8/dist-packages/gridworld/env.py", line 234, in reset
(pid=25888)     obs['pov'] = self.render()[..., :-1]
(pid=25888)   File "/usr/local/lib/python3.8/dist-packages/gridworld/env.py", line 242, in render
(pid=25888)     return self.renderer.render()
(pid=25888)   File "/usr/local/lib/python3.8/dist-packages/gridworld/render.py", line 125, in render
(pid=25888)     return np.asanyarray(
(pid=25888) ValueError: cannot reshape array of size 0 into shape (64,64,4)
```

**Comment by artemZholus** [comment]
Hi, @chenhch8 

This seems weird. Are you able to reproduce this problem with docker?

**Comment by chenhch8** [comment]
I found creating and interacting with the env in the same thread can solve this problem.

**Comment by artemZholus** [comment]
These errors should be fixed now. Please try again, @frankroeder , @chenhch8
