### ISSUE TITLE
`ValueError: cannot reshape array` with `run_env.py`

### ISSUE THREAD

**Issue by felicitywang1** [iglu-contest/gridworld#17]
When I tried to run `run_env.py` I got the following error. I'm running this on Mac OS.
```
(iglu) ➜  examples git:(master) python run_env.py
Traceback (most recent call last):
  File "run_env.py", line 13, in <module>
    env.set_task(DUMMY_TASK)
  File "../gridworld/env.py", line 153, in set_task
    self.reset()
  File "../gridworld/env.py", line 234, in reset
    obs['pov'] = self.render()[..., :-1]
  File "../gridworld/env.py", line 242, in render
    return self.renderer.render()
  File "../gridworld/render.py", line 125, in render
    return np.asanyarray(
ValueError: cannot reshape array of size 65536 into shape (64,64,4)
```

**Comment by artemZholus** [comment]
Hi @felicitywang1 !

It should be fixed now. Please install the latest master and try again.
